### ISSUE TITLE
Change many-to-one implementation in weighted linear influence function

### ISSUE THREAD

**Issue by dimaba** [marijnkeijzer/defSim#12]
The current approach is to take average opinion and average distance in the group, which gives unexpected results when homophily is non-zero and distances are heterogeneous.

https://github.com/marijnkeijzer/defSim/blob/d1333488d2a658e1d68fea69fac4931701d59d72/defSim/influence_sim/WeightedLinear.py#L121-L134

**Comment by dimaba** [comment]
Updated to use mean of influence from all neighbors (taking into account heterogeneity in distances) in 93d502ef3978d928f85cc79048bdeb6bc22d43b1

**Comment by dimaba** [comment]
Bugfix in aa6a46a6ebc8383d2874c41e1a7afd701633fbd4

**Comment by marijnkeijzer** [comment]
What's the (qualitative) difference between the two implementations?

**Comment by dimaba** [comment]
The main difference is in the combination of distance and homophily. 

If homophily == 0, the original implementation works fine because 1 - homophily * distance is equal for all neighbors (homophily * distance is always 0 regardless of distance). Influence from all neighbors then averages out. Also, if homophily != 0 but all neighbors have the same distance from agent_i, it works fine because again 1 - homophily * distance is again equal for all neighbors. In other words, the old and new implementation are equal when either homophily == 0 or distance is constant across all neighbors.

However, when homophily is non-zero and distances differ, neighbors at different distances are supposed to have different strength of influence. By first averaging feature values and distances across all neighbors, the original implementation did not allow for this. In the old implementation, it's basically pretending that all neighbors have the average feature value and average distance from agent_i. 

Here's an example which shows the difference: https://repl.it/repls/DeadSympatheticMicrobsd

**Comment by marijnkeijzer** [comment]
Thanks for the example! Very clear. 

I think the implementation we choose here is a reflection of how we think about 'many-to-one' influence. The old implementation mirrors the idea that people construct a prototypical 'average' agent that is a representation of the agents in the 'many' collection. This resembles the view of for example, the group polarization literature. The new implementation views the 'many' as a set of one-to-one interactions. The big advantage there is that it's a lot closer to one-to-many influence. Arguably, it's one-to-many's inverse. 

At this point, I don't really have a strong opinion on what implementation we should choose, but I do remember a discussion about this early on in the process with Anton and Andreas. The old implementation is thus not a bug but a conscious decision.

Most importantly, we should document this properly so I made a note with exclamation marks to address this thoroughly in the introduction paper.

**Comment by dimaba** [comment]
My intuition would be that it makes the most sense not to have substantive variation between communication regimes within the same influence function. I.e. best to aim for applying exactly the same way to calculate influence, only under a different communication regime. For me, that speaks in favor of the new implementation.

**Comment by marijnkeijzer** [comment]
Yeah I agree :thumbsup:
