### ISSUE TITLE
Allow alternative feature value ranges (outside of the standard [0,1])

### ISSUE THREAD

**Issue by dimaba** [marijnkeijzer/defSim#18]
https://github.com/marijnkeijzer/defSim/blob/aa6a46a6ebc8383d2874c41e1a7afd701633fbd4/defSim/agents_init/agents_init.py#L59

Note that this impacts any default influence functions which presupposes the existence of these bounds, such as WeightedLinear. See also https://github.com/marijnkeijzer/defSim/issues/11

**Comment by dimaba** [comment]
- Not a problem for Bounded Confidence
- Problem for Persuasion: expects communicated arguments to be either 0 or 1

**Comment by dimaba** [comment]
Implemented in 4c6a37d442a2712efb3f9c68c1bc2c8d3b6ac8e3
WeightedLinear influence function updated in 4c6a37d442a2712efb3f9c68c1bc2c8d3b6ac8e3

New issue for updating Persuasion at #19

**Comment by marijnkeijzer** [comment]
As you know I'm not a fan of allowing continuous features to move outside of the 0,1 range. I think it adds unnecessary complexity for the versatility of the other components (both in implementation and testing), as it is simply a matter of scaling and adds no qualitatively different functionality.

Is it okay if I revert the changes?

**Comment by dimaba** [comment]
I'm fine with reverting. Let's start with that. 
Agreed that this may be more complex than it's worth. At the same time, it's not obvious that you should not use the default functions if you initialize agent attributes outside of the range [0, 1] for continuous attributes. For now, I would like to add warnings or errors to the default functions which rely on the [0,1] scale. Maybe at some later point we can revisit other opinion scales, but it's not a crucial feature, so agree to drop it for now.

**Comment by dimaba** [comment]
Reverted changes made for this issue in 9bba61e9ba8c2ddecb54cd01ab9812bac5ac69d0
