### ISSUE TITLE
Add ability to set seed for Experiment class

### ISSUE THREAD

**Issue by dimaba** [marijnkeijzer/defSim#2]

**Comment by dimaba** [comment]
Implemented in 8b96fa0fe5d9195e18217cf3868a919a60992461 with bugfix in 1aeff217ff5fe3c1948f3bc5299a5628a67b7ddb for confusing seed randomization if no seed is specified

**Comment by marijnkeijzer** [comment]
I'm afraid the problem persists: seeding the experiment class works, but results in assiging the same seed for all the simulation runs within the set. This reproduces the issue:

```python
import defSim as ds

test = ds.Experiment(seed=4646,repetitions=2)
test = test.run()

print(test)

test = ds.Experiment(seed=4646,repetitions=2)
test = test.run()

print(test)
```

What we want:
Draw a series of random numbers to seed the different simulation runs, replicable by seeding the experiment class.

**Comment by dimaba** [comment]
Updated in cb097ef4239439d4bba0d8dc8bde6a2579a77dcf
The experiment now generates a sequence of random numbers based on the experiment seed, which are then used as seeds for the individual runs
