### ISSUE TITLE
Scaling of distances

### ISSUE THREAD

**Issue by dimaba** [marijnkeijzer/defSim#20]
The effect of parameters in influence functions changes with the scaling of distance. Example of homophily in WeightedLinear:
https://github.com/marijnkeijzer/defSim/blob/404cfaf046a5e3a1437355c8fba1c9b28ae9c247/defSim/influence_sim/WeightedLinear.py#L111-L114
If the maximum distance possible is different from 1, then the effect of the homophily parameter is not as described. (E.g. negative influence is possible even with homophily values below 1, if the maximum distance possible is greater than 1.) This may be due to a value range other than [0, 1], but can also occur when more than one feature is used. (The Euclidean distance between two agents whose values on two features are [0, 0] and [1, 1] is approximately 1.41. If homophily is set to 1, this will result in a negative weight even though according to the homophily parameter there should be no negative influence.)

To fix this, we should implement some form of distance scaling (where the distance used to compute weights is not the absolute distance, but relative to the maximum distance possible). This means that at some point the maximum possible distance should be determined. Where to do this might take some thinking, because we don't want to impede modularity. (That is: the maximum distance should be available to anyone implementing a custom influence function and should not be some hidden trick that people forget about when implementing distance calculators or influence functions.)

**Comment by dimaba** [comment]
As discussed, if we can safely assume opinion ranges of [0, 1] (see #18) for continuous features we can scale this based on number of features.

**Comment by marijnkeijzer** [comment]
Done 59777694b6eee6ab896a7d4d629233a9a3cd64de
