### ISSUE TITLE
Move convergence checks?

### ISSUE THREAD

**Issue by dimaba** [marijnkeijzer/defSim#23]
The convergence check for running until max iterations is independent of the influence function but this is not the case for pragmatic and strict convergence. Strict convergence clearly depends on the influence function because the influence function determines whether agents can be influenced (e.g. as a result of confidence bounds or zero/negative weights on influence). Pragmatic convergence (checking whether any agent attributes have changed) does not necessarily depend on the influence function, but you may want to specify different pragmatic criteria e.g. when noise is involved. 

Should we move this to a separate class so it can be customized, or perhaps connect to influence functions?

https://github.com/marijnkeijzer/defSim/blob/404cfaf046a5e3a1437355c8fba1c9b28ae9c247/defSim/Simulation.py#L256-L319

**Comment by marijnkeijzer** [comment]
My (late) formal reply:
Creating a class here seems the smartest thing to me. Yes, convergence rules are often linked to influence functions, so integrating the two does make sense in certain cases. However, there are definitely many influence functions that share similar convergence principles. Thus, it makes sense to me to create a class such that 'standard' convergence checks can be used and rewritten when necessary.
