### ISSUE TITLE
Implement 'meaningful' time-estimates in the ds.Experiment.estimate_runtime

### ISSUE THREAD

**Issue by marijnkeijzer** [marijnkeijzer/defSim#3]

**Comment by dimaba** [comment]
Location: https://github.com/marijnkeijzer/defSim/blob/4487ee1e51022a3294f593bd63357afdfaa8b43c/defSim/Experiment.py#L115-L129

**Comment by dimaba** [comment]
Implemented a new method for estimating runtime based on a sample of simulations from the experiment. Works well for simulations which run to max_iterations, not well for simulations which terminate based on other stop conditions.

See 3af61a641d1ffca9333eaa622f4520ff7ef84d1e

**Comment by marijnkeijzer** [comment]
This is beautiful. I updated the docstring.
