### ISSUE TITLE
Make sure that the parameter dictionary created by Experiment does not loop over the list of agent attributes excluded from the dissimilarity calculator

### ISSUE THREAD

**Issue by marijnkeijzer** [marijnkeijzer/defSim#32]
Can't seem to find an elegant solution for this. 

We DO want to include this dictionary (because it needs to go into the parameter_dict and because we might want to loop over other listst included in dissimilarity_parameters.

We DO NOT want to make conditions out of all values in the list 'dissimilarity_exclude'

https://github.com/marijnkeijzer/defSim/blob/39176ad5d5758873184f056637ed0dbf630e65c1/defSim/Experiment.py#L435

**Comment by dimaba** [comment]
Does it work if you set dissimilarity_exclude with a list of lists?
(`'dissimilarity_exclude':[['sex']]`)

If so, you could check whether the value of dissimilarity_exclude is a list of lists (in which case you would leave it as is) or a single list (in which case you would wrap it in another list).

**Comment by marijnkeijzer** [comment]
This has become irrelevant due to the superior solution you proposed.

But in case you're interested: all lists included here are opened such that we iterate over all its items, regardless of the number of lists we embed the elements in.

['foo', 'bar']
returned 
'foo'
'bar'

and 

[[[[['foo, 'bar']]]]]
returned
'foo'
'bar'

and hilariously
'foo'
returned
'f'
'o'
'o'
