### ISSUE TITLE
Examples in repo

### ISSUE THREAD

**Issue by dimaba** [marijnkeijzer/defSim#34]
Since we're working on examples for the different approaches to using defSim, it would make sense to also store these in the repo so users can run them / build on them. 
There's already an examples folder with a UseCases document. 

Is there an existing idea on how examples should be organized? 

https://github.com/marijnkeijzer/defSim/blob/220a9d7e7a45e3de8efa6dcf5e0233a45e9a8e8b/defSim/examples/UseCases.py#L1-L36

**Comment by marijnkeijzer** [comment]
I didn't have an idea about what examples should and what shouldn't be included (maybe @antonlaukemper had?), but actually started working on adding an example from the paper to that folder yesterday.

I would suggest to (1) add the three examples from the paper in separate folders, and (2) add additional examples for implementing your own module for all modules. 

Unless you have a better idea of course. Glad to hear it.

**Comment by marijnkeijzer** [comment]
I now added two examples as ipynb files. I think that is a rather elegant solution as they are very readable and easily shared.

See bdb31579a08b0808cec77d1288965075406c420f

Do you think this is a good solution too?

**Comment by dimaba** [comment]
Yes, looks great! I'll add more in the same style

**Comment by dimaba** [comment]
I think we can consider this closed now. Some examples have been added and we can create more later.
