### ISSUE TITLE
Network modifiers / MS rewiring

### ISSUE THREAD

**Issue by dimaba** [marijnkeijzer/defSim#37]
https://github.com/marijnkeijzer/defSim/blob/62328bc8c38c051a78307ada6a012ba6b3640c58/defSim/network_evolution_sim/NetworkHomophily.py#L6-L15

Question: is NetworkHomophily the best name for this module, given that the only example implementation so far does not include homophily?

https://github.com/marijnkeijzer/defSim/blob/62328bc8c38c051a78307ada6a012ba6b3640c58/defSim/network_init/network_init.py#L263-L288

Suggestion: integrate ms_rewiring from network_init into this NetworkModifier and call that network modifier in network_init (to avoid duplication)

**Comment by marijnkeijzer** [comment]
NetworkHomophily is not a great name, yes. I didn't look at it yet, as the network_evolution_sim part is still only a placeholder anyway. Feel free to change as you please!

About the suggestion: yes yes yes! And you did it :)
