### ISSUE TITLE
Should non-specified seed for simulations be random by run or by session?

### ISSUE THREAD

**Issue by dimaba** [marijnkeijzer/defSim#9]
https://github.com/marijnkeijzer/defSim/blob/bab912aa084de04dcf3e3fa136e53ef44e19a6e5/defSim/Simulation.py#L65

A default random seed is implemented in the Simulation class. However, this random.randint() runs when the _class_ is initialized. It is then fixed for any instances of Simulation created until the Python interpreter is restarted.

This could be considered a bug (if you want a random seed for each new simulation run unless otherwise specified) or a feature (if you want repeatability for multiple runs unless otherwise specified). I'm leaning towards bug, since I think you would expect each simulation to be randomly seeded unless the seed is intentionally fixed. 

Another reason to call this a bug is that it's currently causing unexpected behavior: if you explicitly set seed to None when creating the Simulation instance, the seed _is_ random. 

https://github.com/marijnkeijzer/defSim/blob/bab912aa084de04dcf3e3fa136e53ef44e19a6e5/defSim/Simulation.py#L141-L142

I will implement randomness by default for now, but leaving this here for possible conversation.

**Comment by dimaba** [comment]
Implemented in 1aeff217ff5fe3c1948f3bc5299a5628a67b7ddb

**Comment by marijnkeijzer** [comment]
Links to this discussion: #2 

I'm not sure I can understand the issue with the original implementation fully. A call to the experiment function without seeding that function always resulted in a set of simulation runs with different seeds if this is what you imply the bug would have been.

However, we do need to make sure that we can seed the Experiment class when drawing seeds for the instances of Simulation run. Perhaps we can do this when constructing the paramDictList.

**Comment by dimaba** [comment]
> I'm not sure I can understand the issue with the original implementation fully. A call to the experiment function without seeding that function always resulted in a set of simulation runs with different seeds if this is what you imply the bug would have been.

This possibly worked from the experiment class, but the issue was this:

Running several simulations in one script without using the experiment class, so something like
```python
sim1 = Simulation(...,some_parameters={})
sim2 = Simulation(...,some_other_parameters={})
```
where neither simulation has a seed specified would result in both simulations running with the same seed. This is because the selection of the default random seed being specified in the parameter values for the __init__ function of the Simulation class. Because the function definition (and therefore the determination of default values) runs once (off the top of my head: the first time the class is used), the default value is the same for all simulations until the Python interpreter restarts. 

With the changed implementation, there is a new call to random.randint whenever a new instance of the class is created, so multiple simulations in the same script run with different seeds.

See https://repl.it/repls/DismalDarkturquoiseChord for illustration of the difference

**Comment by marijnkeijzer** [comment]
Ah I see, that makes sense. Thanks!
